### ISSUE TITLE
unbundle of CCAT on Debian Jessie

### ISSUE THREAD

**Issue by JJHelfrich** [Beckhoff/CCAT#4]
I am trying to get my Beckhoff CX2030 with Debian Jessie running using CCAT modules. Here is my process for acquiring Etherlab and CCAT. 

The problem arises when I try to unbundle the etherlab.bundle

`hg clone http://hg.code.sf.net/p/etherlabmaster/code ethercat-hg`
`cd ethercat-hg`
`hg update stable-1.5`

`wget https://github.com/Beckhoff/CCAT/blob/master/etherlab.bundle`
`hg unbundle etherlab.bundle`

The error I receive is:
`abort: etherlab.bundle: unknown bundle version 20`

Do you know what might cause this, or how to solve?

**Comment by pbruenn** [comment]
try: `wget https://github.com/Beckhoff/CCAT/raw/master/etherlab.bundle`
The downloaded file should be 867 bytes in size.
However that bundle does only contain a patch [1] for kernel 4.10, so if you use an older kernel, you don't even need the bundle.

[1] http://lists.etherlab.org/pipermail/etherlab-dev/2017/000573.html

**Comment by JJHelfrich** [comment]
That makes more sense! 
As you stated, I got it working without the patch.

My version of Mercurial in Debian was too old, and it wouldn't let me unbundle. The version available for Jessie has a backport.

To enable:
`echo deb http://http.debian.net/debian jessie-backports main > /etc/apt/sources.list.d/jessie-backports.list`

`apt-get update`

Then upgrade Mercurial:
`apt-get -t jessie-backports install mercurial`
