### ISSUE TITLE
unittest failing

### ISSUE THREAD

**Issue by jbodart** [Beckhoff/CCAT#5]
When I try to run "make unittest", i get a "chmod: cannot access '/dev/ccat_*': no such file or directory.
I am not sure of what it means. I get no complain at make/make install

**Comment by pbruenn** [comment]
The error indicates there are no device files created for ccat devices.
On which hardware do you run this?
What output do you get in dmesg , when you run make install?

**Comment by jbodart** [comment]
Nothing in dmesg during make install.
hardware CX5140, running ubuntu server 18.04 with RT kernel 4.9.115.

It seems I have 3 ethernets port recognized (w or wo ccat).

dmesg |grep eth
[    5.415586] igb 0000:01:00.0: added PHC on eth1
[    5.423192] igb 0000:01:00.0: eth1: (PCIe:2.5Gb/s:Width x1) 00:01:05:1e:e4:ba
[    5.425704] ec_bhf 0000:03:00.0 enp3s0: renamed from eth0
[    5.430730] igb 0000:01:00.0: eth1: PBA No: 001300-000
[    5.684030] igb 0000:02:00.0: added PHC on eth0
[    5.691689] igb 0000:02:00.0: eth0: (PCIe:2.5Gb/s:Width x1) 00:01:05:1e:e4:bb
[    5.695554] igb 0000:02:00.0: eth0: PBA No: 001300-000
[    5.738008] igb 0000:02:00.0 enp2s0: renamed from eth0
[    5.772133] igb 0000:01:00.0 enp1s0: renamed from eth1

**Comment by pbruenn** [comment]
Oh yes of course, the problem is "ec_bhf". See this answer:
https://github.com/Beckhoff/CCAT/issues/3#issuecomment-266788708

**Comment by jbodart** [comment]
aaahhhhh. I feel so bad. I did not look at the issues as I saw 0 open issues.
Indeed that was the problem. That solves the problem with my ethercat master (KPA) as well

**Comment by pbruenn** [comment]
No problem, it took me a while to remember, too ;-)
