### ISSUE TITLE
CCAT: ubuntu 20.04 kernel modules don't load

### ISSUE THREAD

**Issue by gcorrente** [Beckhoff/CCAT#8]
Hello,

After compiling the drivers (with UBUNTU 20.04) the drivers don't load.
error:

`
[ 5412.520911] ccat_gpio: loading out-of-tree module taints kernel.

[ 5412.520979] ccat_gpio: module verification failed: signature and/or required key missing - tainting kernel

[ 5412.521157] ccat_gpio: unknown parameter 'ccat' ignored

[ 5412.521159] ccat_gpio: unknown parameter 'ccat_netdev' ignored

[ 5412.521164] ccat_gpio: unknown parameter 'ccat_sram' ignored

[ 5412.521166] ccat_gpio: unknown parameter 'ccat_systemtime' ignored

[ 5412.521167] ccat_gpio: unknown parameter 'ccat_update' ignored
` 

Regards,

Gustavo

**Comment by pbruenn** [comment]
Did you blacklist ec_bhf?
See https://github.com/Beckhoff/CCAT/issues/3#issuecomment-266788708

**Comment by gcorrente** [comment]
Hello,

I forgot: CX5130-0120, running linux from compact flash.
Was that. all thing is loaded. Thks. 

two 2 questions:
- where I found ecrt.h file
- do you have examples reading/writing using c code?

Regards,
Gustavo

**Comment by pbruenn** [comment]
Ecrt.h is Part of EtherLab:
https://www.etherlab.org/en/ethercat/index.php
They have examples and and a pretty helpful mailing list if you want run an EtherCAT Master on Linux
